/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package popup;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import rekapanggaran.EntryDataGaji;
import rekapanggaran.Koneksi;

/**
 *
 * @author BadikIrwan
 */
public class EntryGajiDetail extends javax.swing.JDialog {

    Connection con = Koneksi.connect();
    private final EntryDataGaji form;
    private JCheckBox[] pilihan; 
    int a = 0;
    private int Senin;
    private int Selasa;
    private int Rabu;
    private int Kamis;
    private int Jumat;
    private int Sabtu;
    private String nama;
    private String gaji;
    private String lmbr;
    private String bonus;
    private String gajilembur;
    private String potongan;
    private String jumlah;
    private String hadir;
    private String ID;
    private Object status;
    private Statement st;
    private int mbonus;
    private int mpotongan;
    private String query;

    /**
     * Creates new form EntryDataGaji
     * @param parent
     * @param modal
     * @param form
     */
    public EntryGajiDetail(java.awt.Frame parent, boolean modal, EntryDataGaji form) {
        super(parent, modal);
        this.form = form;
        initComponents();
        //loadData();
    }

    private EntryGajiDetail(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbPekerjaan = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbLokasi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbNamacv = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbTanggal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbTahun = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbMingguke = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtxNama = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtGaji = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbSenin = new javax.swing.JCheckBox();
        cbSelasa = new javax.swing.JCheckBox();
        cbRabu = new javax.swing.JCheckBox();
        cbKamis = new javax.swing.JCheckBox();
        cbJumat = new javax.swing.JCheckBox();
        cbSabtu = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        txtLembur = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTotalLembur = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtBonus = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtPotongan = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        lembur = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        id = new javax.swing.JLabel();
        id1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        id2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detail Data Gaji");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Peket Pekerjaan ");

        lbPekerjaan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbPekerjaan.setText("-");

        jLabel3.setText("Lokasi");

        lbLokasi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbLokasi.setText("-");

        jLabel5.setText("Nama CV");

        lbNamacv.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbNamacv.setText("-");

        jLabel7.setText("Tanggal");

        lbTanggal.setText("-");

        jLabel9.setText("Tahun");

        lbTahun.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTahun.setText("-");

        jLabel11.setText("Minggu Ke");

        lbMingguke.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbMingguke.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPekerjaan)
                    .addComponent(lbLokasi)
                    .addComponent(lbNamacv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(97, 97, 97)
                            .addComponent(lbTanggal))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(105, 105, 105)
                            .addComponent(lbTahun)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(86, 86, 86)
                        .addComponent(lbMingguke)))
                .addGap(132, 132, 132))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbPekerjaan)
                    .addComponent(jLabel7)
                    .addComponent(lbTanggal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbLokasi)
                    .addComponent(jLabel9)
                    .addComponent(lbTahun))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbNamacv)
                    .addComponent(jLabel11)
                    .addComponent(lbMingguke))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setText("Nama");

        jLabel14.setText("Gaji");

        txtGaji.setText("0");
        txtGaji.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGajiKeyReleased(evt);
            }
        });

        jLabel15.setText("Status");

        jLabel16.setText("Hari");

        cbSenin.setText("Senin");
        cbSenin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbSeninMouseClicked(evt);
            }
        });
        cbSenin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSeninItemStateChanged(evt);
            }
        });

        cbSelasa.setText("Selasa");
        cbSelasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbSelasaMouseClicked(evt);
            }
        });
        cbSelasa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSelasaItemStateChanged(evt);
            }
        });

        cbRabu.setText("Rabu");
        cbRabu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbRabuMouseClicked(evt);
            }
        });
        cbRabu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRabuItemStateChanged(evt);
            }
        });

        cbKamis.setText("Kamis");
        cbKamis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbKamisMouseClicked(evt);
            }
        });
        cbKamis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbKamisItemStateChanged(evt);
            }
        });

        cbJumat.setText("Jum'at");
        cbJumat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbJumatMouseClicked(evt);
            }
        });
        cbJumat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbJumatItemStateChanged(evt);
            }
        });

        cbSabtu.setText("Sabtu");
        cbSabtu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbSabtuMouseClicked(evt);
            }
        });
        cbSabtu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSabtuItemStateChanged(evt);
            }
        });

        jLabel17.setText("Lembur");

        txtLembur.setText("0");
        txtLembur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLemburKeyReleased(evt);
            }
        });

        jLabel18.setText("HARI/JAM");

        txtTotalLembur.setText("0");
        txtTotalLembur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotalLemburKeyReleased(evt);
            }
        });

        jLabel19.setText("Bonus");

        txtBonus.setText("0");
        txtBonus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBonusKeyReleased(evt);
            }
        });

        jLabel20.setText("Potongan");

        txtPotongan.setText("0");
        txtPotongan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPotonganKeyReleased(evt);
            }
        });

        jLabel21.setText("Jumlah");

        txtJumlah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtJumlah.setText("0");
        txtJumlah.setEnabled(false);

        lembur.setText("0");
        lembur.setMaximumSize(new java.awt.Dimension(0, 0));
        lembur.setMinimumSize(new java.awt.Dimension(0, 0));

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "Tukang", "Kuli" }));

        id.setText("0");
        id.setMaximumSize(new java.awt.Dimension(0, 0));
        id.setMinimumSize(new java.awt.Dimension(0, 0));

        id1.setText("0");
        id1.setMaximumSize(new java.awt.Dimension(0, 0));
        id1.setMinimumSize(new java.awt.Dimension(0, 0));

        jLabel22.setText("Gaji Lembur");

        id2.setText("0");
        id2.setMaximumSize(new java.awt.Dimension(0, 0));
        id2.setMinimumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtxNama, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addComponent(txtGaji))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbKamis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbJumat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSabtu)))
                        .addGap(176, 176, 176)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(txtPotongan, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBonus)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtLembur, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel18))
                                    .addComponent(txtTotalLembur, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbSenin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbSelasa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbRabu))
                            .addComponent(cbStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addComponent(lembur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(331, 331, 331)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(355, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(341, 341, 341)
                    .addComponent(id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(345, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(351, Short.MAX_VALUE)
                    .addComponent(id2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(335, 335, 335)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtxNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtLembur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txtGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTotalLembur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19)
                    .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lembur, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cbSenin)
                    .addComponent(cbSelasa)
                    .addComponent(cbRabu)
                    .addComponent(jLabel20)
                    .addComponent(txtPotongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKamis)
                    .addComponent(cbJumat)
                    .addComponent(cbSabtu)
                    .addComponent(jLabel21)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(73, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(83, Short.MAX_VALUE)
                    .addComponent(id1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(65, 65, 65)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(95, Short.MAX_VALUE)
                    .addComponent(id2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(55, 55, 55)))
        );

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAMA", "KERJA", "LEMBUR", "GAJI LEMBUR", "BONUS", "POTONGAN", "TOTAL"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        btnSimpan.setText("Tambah");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        Clear();
        try {
            int row = tabel.getSelectedRow();
            String tabel_klik = tabel.getModel().getValueAt(row, 0).toString();
            Connection con = Koneksi.connect();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM tbl_gaji_detail WHERE id='"+tabel_klik+"'");
            if(rs.next()) {
                id.setText(rs.getString("id"));
                id1.setText(rs.getString("id_gaji"));
                txtxNama.setText(rs.getString("nama"));
                txtGaji.setText(rs.getString("gaji"));
                cbStatus.setSelectedItem(rs.getString("status"));
                if(rs.getString("senin").equals("1")) cbSenin.setSelected(true);
                if(rs.getString("selasa").equals("1")) cbSelasa.setSelected(true);
                if(rs.getString("rabu").equals("1")) cbRabu.setSelected(true);
                if(rs.getString("kamis").equals("1")) cbKamis.setSelected(true);
                if(rs.getString("jumat").equals("1")) cbJumat.setSelected(true);
                if(rs.getString("sabtu").equals("1")) cbSabtu.setSelected(true);
                txtLembur.setText(rs.getString("lembur"));
                txtTotalLembur.setText(rs.getString("gaji_lembur"));
                txtBonus.setText(rs.getString("bonus"));
                txtPotongan.setText(rs.getString("potongan"));
                txtJumlah.setText(rs.getString("jumlah"));
            }
            btnSimpan.setText("Simpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void txtLemburKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLemburKeyReleased
        if(txtLembur.getText().isEmpty()) {            
            //txtTotalLembur.setText(String.valueOf("0"));
            int mgaji = Integer.parseInt(txtGaji.getText());
            int mjumlah = Integer.parseInt(lembur.getText());
            int mtlembur = Integer.parseInt(txtTotalLembur.getText());
            if(txtBonus.getText().isEmpty()){
                mbonus = 0;
            } else {
            mbonus = Integer.parseInt(txtBonus.getText());
            }
            if(txtPotongan.getText().isEmpty()){
                mpotongan = 0;
            } else {
                mpotongan = Integer.parseInt(txtPotongan.getText());
            }
            int result = (mjumlah*mgaji)+mtlembur+mbonus-mpotongan;
            txtJumlah.setText(String.valueOf(result));
        } else {
            int a = Integer.parseInt(txtLembur.getText());
            int b = Integer.parseInt(txtTotalLembur.getText());
            int hasil = a*b;
            int mgaji = Integer.parseInt(txtGaji.getText());
            int mjumlah = Integer.parseInt(lembur.getText());
            int mtlembur = hasil;
            if(txtBonus.getText().isEmpty()){
                mbonus = 0;
            } else {
            mbonus = Integer.parseInt(txtBonus.getText());
            }
            if(txtPotongan.getText().isEmpty()){
                mpotongan = 0;
            } else {
                mpotongan = Integer.parseInt(txtPotongan.getText());
            }
            int result = (mjumlah*mgaji)+mtlembur+mbonus-mpotongan;
            txtJumlah.setText(String.valueOf(result));
        }
    }//GEN-LAST:event_txtLemburKeyReleased

    private void cbSeninItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSeninItemStateChanged
        if(cbSenin.isSelected()) {
            a++;
            lembur.setText(String.valueOf(a));
        } else {
            a--;
            lembur.setText(String.valueOf(a));
        }
    }//GEN-LAST:event_cbSeninItemStateChanged

    private void cbSelasaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSelasaItemStateChanged
        if(cbSelasa.isSelected()) {
            a++;
            lembur.setText(String.valueOf(a));
        } else {
            a--;
            lembur.setText(String.valueOf(a));
        }
    }//GEN-LAST:event_cbSelasaItemStateChanged

    private void cbRabuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRabuItemStateChanged
        if(cbRabu.isSelected()) {
            a++;
            lembur.setText(String.valueOf(a));
        } else {
            a--;
            lembur.setText(String.valueOf(a));
        }
    }//GEN-LAST:event_cbRabuItemStateChanged

    private void cbKamisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbKamisItemStateChanged
        if(cbKamis.isSelected()) {
            a++;
            lembur.setText(String.valueOf(a));
        } else {
            a--;
            lembur.setText(String.valueOf(a));
        }
    }//GEN-LAST:event_cbKamisItemStateChanged

    private void cbJumatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbJumatItemStateChanged
        if(cbJumat.isSelected()) {
            a++;
            lembur.setText(String.valueOf(a));
        } else {
            a--;
            lembur.setText(String.valueOf(a));
        }
    }//GEN-LAST:event_cbJumatItemStateChanged

    private void cbSabtuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSabtuItemStateChanged
        if(cbSabtu.isSelected()) {
            a++;
            lembur.setText(String.valueOf(a));
        } else {
            a--;
            lembur.setText(String.valueOf(a));
        }
    }//GEN-LAST:event_cbSabtuItemStateChanged

    private void txtPotonganKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPotonganKeyReleased
        if(txtPotongan.getText().isEmpty()) {
            int mgaji = Integer.parseInt(txtGaji.getText());
            int mjumlah = Integer.parseInt(lembur.getText());
            int mtlembur = Integer.parseInt(txtTotalLembur.getText());
            int mbonus = Integer.parseInt(txtBonus.getText());
            int mpotongan = 0;
            int result = (mjumlah*mgaji)+mtlembur+mbonus-mpotongan;
            txtJumlah.setText(String.valueOf(result));
        } else {
            int mgaji = Integer.parseInt(txtGaji.getText());
            int mjumlah = Integer.parseInt(lembur.getText());
            int mtlembur = Integer.parseInt(txtTotalLembur.getText());
            int mbonus = Integer.parseInt(txtBonus.getText());
            int mpotongan = Integer.parseInt(txtPotongan.getText());
            int result = (mjumlah*mgaji)+mtlembur+mbonus-mpotongan;
            txtJumlah.setText(String.valueOf(result));         
        }
    }//GEN-LAST:event_txtPotonganKeyReleased

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if(cbSenin.isSelected()) {Senin = 1;} else {Senin = 0;}
        if(cbSelasa.isSelected()) {Selasa = 1;} else {Selasa = 0;}
        if(cbRabu.isSelected()) {Rabu = 1;} else {Rabu = 0;}
        if(cbKamis.isSelected()) {Kamis = 1;} else {Kamis = 0;}
        if(cbJumat.isSelected()) {Jumat = 1;} else {Jumat = 0;}
        if(cbSabtu.isSelected()) {Sabtu = 1;} else {Sabtu = 0;}
        ID = id1.getText();
        hadir = lembur.getText();
        nama = txtxNama.getText();
        status = cbStatus.getSelectedItem();
        gaji = txtGaji.getText();
        lmbr = txtLembur.getText();
        gajilembur = txtTotalLembur.getText();
        bonus = txtBonus.getText();
        potongan = txtPotongan.getText();
        jumlah = txtJumlah.getText();
        
        if(btnSimpan.getText().equals("Tambah")) {
            try {               
                Statement st = con.createStatement();
                String query = "INSERT INTO tbl_gaji_detail (id_gaji, nama, status, gaji, senin, selasa, rabu, kamis, jumat, sabtu, hadir, lembur, gaji_lembur, bonus, potongan, jumlah) "
                    + "VALUES ('"+ID+"', '"+nama+"', '"+status+"', '"+gaji+"', '"+Senin+"', '"+Selasa+"', '"+Rabu+"', '"+Kamis+"', '"+Jumat+"', '"+Sabtu+"', '"+hadir+"', '"+lmbr+"', '"+gajilembur+"', '"+bonus+"', '"+potongan+"', '"+jumlah+"')";
                st.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "Data Berhasil ditambahkan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Pesan", JOptionPane.INFORMATION_MESSAGE);
            }
            loadData();
            Clear();
        } else {
            try {
                st = con.createStatement();
                String query;
                query = "UPDATE tbl_gaji_detail SET id_gaji='"+id1.getText()+"',nama='"+nama+"',status='"+status+"',gaji='"+gaji+"',senin='"+Senin+"',selasa='"+Selasa+"',rabu='"+Rabu+"',kamis='"+Kamis+"',jumat='"+Jumat+"',sabtu='"+Sabtu+"',"
                        + "hadir='"+hadir+"',lembur='"+lmbr+"',gaji_lembur='"+gajilembur+"',bonus='"+bonus+"',potongan='"+potongan+"',jumlah='"+jumlah+"' WHERE id='"+id.getText()+"'";               
                st.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "Data Berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Pesan", JOptionPane.INFORMATION_MESSAGE);
            } 
            btnSimpan.setText("Tambah");
            loadData();
            Clear();
        }
        loadData();
        Clear();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        form.loadData();
        kosongkanTable();
        Clear();
    }//GEN-LAST:event_formWindowClosing

    private void cbSelasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbSelasaMouseClicked
        hitung();
    }//GEN-LAST:event_cbSelasaMouseClicked

    private void txtGajiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGajiKeyReleased
        hitung();
    }//GEN-LAST:event_txtGajiKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Clear();
        btnSimpan.setText("Tambah");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            Connection con = Koneksi.connect();
            Statement st = con.createStatement();
            String query = "DELETE FROM tbl_gaji_detail WHERE id='"+id.getText()+"'";
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Data Berhasil dihapus", "Pesan", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Pesan", JOptionPane.INFORMATION_MESSAGE);
        }
        btnSimpan.setText("Tambah");
        loadData();
        Clear();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtBonusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBonusKeyReleased
        hitung();
    }//GEN-LAST:event_txtBonusKeyReleased

    private void cbSeninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbSeninMouseClicked
        hitung();
    }//GEN-LAST:event_cbSeninMouseClicked

    private void cbRabuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbRabuMouseClicked
        hitung();
    }//GEN-LAST:event_cbRabuMouseClicked

    private void cbKamisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbKamisMouseClicked
        hitung();
    }//GEN-LAST:event_cbKamisMouseClicked

    private void cbJumatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbJumatMouseClicked
        hitung();
    }//GEN-LAST:event_cbJumatMouseClicked

    private void cbSabtuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbSabtuMouseClicked
        hitung();
    }//GEN-LAST:event_cbSabtuMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        loadData();
    }//GEN-LAST:event_formWindowOpened

    private void txtTotalLemburKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalLemburKeyReleased
        if(txtTotalLembur.getText().isEmpty()) {            
            //txtTotalLembur.setText(String.valueOf("0"));
            int mgaji = Integer.parseInt(txtGaji.getText());
            int mjumlah = Integer.parseInt(lembur.getText());
            int mtlembur = Integer.parseInt(txtTotalLembur.getText());
            if(txtBonus.getText().isEmpty()){
                mbonus = 0;
            } else {
            mbonus = Integer.parseInt(txtBonus.getText());
            }
            if(txtPotongan.getText().isEmpty()){
                mpotongan = 0;
            } else {
                mpotongan = Integer.parseInt(txtPotongan.getText());
            }
            int result = (mjumlah*mgaji)+mtlembur+mbonus-mpotongan;
            txtJumlah.setText(String.valueOf(result));
        } else {
            int a = Integer.parseInt(txtLembur.getText());
            int b = Integer.parseInt(txtTotalLembur.getText());
            int hasil = a*b;
            int mgaji = Integer.parseInt(txtGaji.getText());
            int mjumlah = Integer.parseInt(lembur.getText());
            int mtlembur = hasil;
            if(txtBonus.getText().isEmpty()){
                mbonus = 0;
            } else {
            mbonus = Integer.parseInt(txtBonus.getText());
            }
            if(txtPotongan.getText().isEmpty()){
                mpotongan = 0;
            } else {
                mpotongan = Integer.parseInt(txtPotongan.getText());
            }
            int result = (mjumlah*mgaji)+mtlembur+mbonus-mpotongan;
            txtJumlah.setText(String.valueOf(result));
        }
    }//GEN-LAST:event_txtTotalLemburKeyReleased

    private void hitung() {
        int mgaji, jmlembur, glembur, mbonus, mpotongan, mjumlah, masuk;
        if(lembur.getText().isEmpty()){
            masuk = 0;
        } else {
            masuk = Integer.parseInt(lembur.getText());
        }
        if(txtGaji.getText().isEmpty()){
            mgaji = 0;
        } else {
            mgaji = Integer.parseInt(txtGaji.getText());
        }
        if(txtLembur.getText().isEmpty()){
            jmlembur = 0;
        } else {
            jmlembur = Integer.parseInt(txtLembur.getText());
        }
        if(txtTotalLembur.getText().isEmpty()){
            glembur = 0;
        } else {
            glembur = Integer.parseInt(txtTotalLembur.getText());
        }
        if(txtBonus.getText().isEmpty()){
            mbonus = 0;
        } else {
            mbonus = Integer.parseInt(txtBonus.getText());
        }
        if(txtPotongan.getText().isEmpty()){
            mpotongan = 0;
        } else {
            mpotongan = Integer.parseInt(txtPotongan.getText());
        }
        if(txtJumlah.getText().isEmpty()){
            mjumlah = 0;
        } else {
            mjumlah = Integer.parseInt(txtJumlah.getText());
        }
        int hasil = (mgaji*masuk)+glembur+mbonus-mpotongan;
        txtJumlah.setText(String.valueOf(hasil));
    }
    
    private void kosongkanTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("NAMA");
        model.addColumn("KERJA");
        model.addColumn("LEMBUR");
        model.addColumn("GAJI LEMBUR");
        model.addColumn("BONUS");
        model.addColumn("POTONGAN");
        model.addColumn("TOTAL");
        tabel.setModel(model);
    }
    public void loadData() {
       DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("NAMA");
        model.addColumn("KERJA");
        model.addColumn("LEMBUR");
        model.addColumn("GAJI LEMBUR");
        model.addColumn("BONUS");
        model.addColumn("POTONGAN");
        model.addColumn("TOTAL");
        try {
            Connection con = Koneksi.connect();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM tbl_gaji_detail WHERE id_gaji='"+id1.getText()+"'");
            while(rs.next()) {
               model.addRow(new Object[]{
               rs.getString("id"), rs.getString("nama"), rs.getString("hadir")+" HARI", rs.getString("lembur")+" HARI/JAM",
               rs.getString("gaji_lembur"), rs.getString("bonus"), rs.getString("potongan"), rs.getString("jumlah")});
               tabel.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        } 
    }
    
    public void Clear() {
        id.setText("");
        lembur.setText("");
        txtxNama.setText("");
        cbStatus.setSelectedIndex(0);
        txtGaji.setText("0");
        txtLembur.setText("0");
        txtTotalLembur.setText("0");
        txtBonus.setText("0");
        txtPotongan.setText("0");
        txtJumlah.setText("0");
        cbSenin.setSelected(false);
        cbSelasa.setSelected(false);
        cbRabu.setSelected(false);
        cbKamis.setSelected(false);
        cbJumat.setSelected(false);
        cbSabtu.setSelected(false);
    }
    
    public void Kode() {
        try {
           Connection con = Koneksi.connect();
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery("SELECT MAX(id_kegiatan) FROM tbl_gaji_detail");
           while(rs.next()) {
               int a = rs.getInt(1);
               id2.setText("000"+Integer.toString(a+1));
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Pesan", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntryGajiDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntryGajiDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntryGajiDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntryGajiDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EntryGajiDetail dialog = new EntryGajiDetail(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JCheckBox cbJumat;
    private javax.swing.JCheckBox cbKamis;
    private javax.swing.JCheckBox cbRabu;
    private javax.swing.JCheckBox cbSabtu;
    private javax.swing.JCheckBox cbSelasa;
    private javax.swing.JCheckBox cbSenin;
    private javax.swing.JComboBox<String> cbStatus;
    public javax.swing.JLabel id;
    public javax.swing.JLabel id1;
    public javax.swing.JLabel id2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lbLokasi;
    public javax.swing.JLabel lbMingguke;
    public javax.swing.JLabel lbNamacv;
    public javax.swing.JLabel lbPekerjaan;
    public javax.swing.JLabel lbTahun;
    public javax.swing.JLabel lbTanggal;
    private javax.swing.JLabel lembur;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField txtBonus;
    private javax.swing.JTextField txtGaji;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtLembur;
    private javax.swing.JTextField txtPotongan;
    private javax.swing.JTextField txtTotalLembur;
    private javax.swing.JTextField txtxNama;
    // End of variables declaration//GEN-END:variables
}
